//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceptedConfiguration) DeepCopyInto(out *AcceptedConfiguration) {
	*out = *in
	in.Whitelist.DeepCopyInto(&out.Whitelist)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceptedConfiguration.
func (in *AcceptedConfiguration) DeepCopy() *AcceptedConfiguration {
	if in == nil {
		return nil
	}
	out := new(AcceptedConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppliedConfiguration) DeepCopyInto(out *AppliedConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppliedConfiguration.
func (in *AppliedConfiguration) DeepCopy() *AppliedConfiguration {
	if in == nil {
		return nil
	}
	out := new(AppliedConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletionStatus) DeepCopyInto(out *DeletionStatus) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletionStatus.
func (in *DeletionStatus) DeepCopy() *DeletionStatus {
	if in == nil {
		return nil
	}
	out := new(DeletionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyProcessStatus) DeepCopyInto(out *EnvoyProcessStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyProcessStatus.
func (in *EnvoyProcessStatus) DeepCopy() *EnvoyProcessStatus {
	if in == nil {
		return nil
	}
	out := new(EnvoyProcessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkStatus) DeepCopyInto(out *NetworkStatus) {
	*out = *in
	if in.VerifiedAt != nil {
		in, out := &in.VerifiedAt, &out.VerifiedAt
		*out = (*in).DeepCopy()
	}
	if in.EnvoyProcesses != nil {
		in, out := &in.EnvoyProcesses, &out.EnvoyProcesses
		*out = make([]EnvoyProcessStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkStatus.
func (in *NetworkStatus) DeepCopy() *NetworkStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStatus) DeepCopyInto(out *NodeStatus) {
	*out = *in
	if in.Termination != nil {
		in, out := &in.Termination, &out.Termination
		*out = new(ProcessTermination)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStatus.
func (in *NodeStatus) DeepCopy() *NodeStatus {
	if in == nil {
		return nil
	}
	out := new(NodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessIdentity) DeepCopyInto(out *ProcessIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessIdentity.
func (in *ProcessIdentity) DeepCopy() *ProcessIdentity {
	if in == nil {
		return nil
	}
	out := new(ProcessIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessTermination) DeepCopyInto(out *ProcessTermination) {
	*out = *in
	in.FinishedAt.DeepCopyInto(&out.FinishedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessTermination.
func (in *ProcessTermination) DeepCopy() *ProcessTermination {
	if in == nil {
		return nil
	}
	out := new(ProcessTermination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceCredentials) DeepCopyInto(out *ServiceCredentials) {
	*out = *in
	if in.OperatorPassword != nil {
		in, out := &in.OperatorPassword, &out.OperatorPassword
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.ReplicaPassword != nil {
		in, out := &in.ReplicaPassword, &out.ReplicaPassword
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.HealthPassword != nil {
		in, out := &in.HealthPassword, &out.HealthPassword
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.UsersACL != nil {
		in, out := &in.UsersACL, &out.UsersACL
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceCredentials.
func (in *ServiceCredentials) DeepCopy() *ServiceCredentials {
	if in == nil {
		return nil
	}
	out := new(ServiceCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeyInstance) DeepCopyInto(out *ValkeyInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeyInstance.
func (in *ValkeyInstance) DeepCopy() *ValkeyInstance {
	if in == nil {
		return nil
	}
	out := new(ValkeyInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ValkeyInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeyInstanceList) DeepCopyInto(out *ValkeyInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ValkeyInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeyInstanceList.
func (in *ValkeyInstanceList) DeepCopy() *ValkeyInstanceList {
	if in == nil {
		return nil
	}
	out := new(ValkeyInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ValkeyInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeyInstanceSpec) DeepCopyInto(out *ValkeyInstanceSpec) {
	*out = *in
	if in.Whitelist != nil {
		in, out := &in.Whitelist, &out.Whitelist
		*out = new(WhitelistSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeyInstanceSpec.
func (in *ValkeyInstanceSpec) DeepCopy() *ValkeyInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(ValkeyInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeyInstanceStatus) DeepCopyInto(out *ValkeyInstanceStatus) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.PrimaryOrdinal != nil {
		in, out := &in.PrimaryOrdinal, &out.PrimaryOrdinal
		*out = new(int32)
		**out = **in
	}
	if in.AcceptedConfiguration != nil {
		in, out := &in.AcceptedConfiguration, &out.AcceptedConfiguration
		*out = new(AcceptedConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Applied != nil {
		in, out := &in.Applied, &out.Applied
		*out = new(AppliedConfiguration)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Deletion != nil {
		in, out := &in.Deletion, &out.Deletion
		*out = new(DeletionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeyInstanceStatus.
func (in *ValkeyInstanceStatus) DeepCopy() *ValkeyInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(ValkeyInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WhitelistSpec) DeepCopyInto(out *WhitelistSpec) {
	*out = *in
	if in.CIDRs != nil {
		in, out := &in.CIDRs, &out.CIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WhitelistSpec.
func (in *WhitelistSpec) DeepCopy() *WhitelistSpec {
	if in == nil {
		return nil
	}
	out := new(WhitelistSpec)
	in.DeepCopyInto(out)
	return out
}
