//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceptedConfiguration) DeepCopyInto(out *AcceptedConfiguration) {
	*out = *in
	in.Whitelist.DeepCopyInto(&out.Whitelist)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceptedConfiguration.
func (in *AcceptedConfiguration) DeepCopy() *AcceptedConfiguration {
	if in == nil {
		return nil
	}
	out := new(AcceptedConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppliedConfiguration) DeepCopyInto(out *AppliedConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppliedConfiguration.
func (in *AppliedConfiguration) DeepCopy() *AppliedConfiguration {
	if in == nil {
		return nil
	}
	out := new(AppliedConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialRotationConfirmation) DeepCopyInto(out *CredentialRotationConfirmation) {
	*out = *in
	out.Process = in.Process
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialRotationConfirmation.
func (in *CredentialRotationConfirmation) DeepCopy() *CredentialRotationConfirmation {
	if in == nil {
		return nil
	}
	out := new(CredentialRotationConfirmation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialRotationStatus) DeepCopyInto(out *CredentialRotationStatus) {
	*out = *in
	if in.Confirmations != nil {
		in, out := &in.Confirmations, &out.Confirmations
		*out = make([]CredentialRotationConfirmation, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialRotationStatus.
func (in *CredentialRotationStatus) DeepCopy() *CredentialRotationStatus {
	if in == nil {
		return nil
	}
	out := new(CredentialRotationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeletionStatus) DeepCopyInto(out *DeletionStatus) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeletionStatus.
func (in *DeletionStatus) DeepCopy() *DeletionStatus {
	if in == nil {
		return nil
	}
	out := new(DeletionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyProcessStatus) DeepCopyInto(out *EnvoyProcessStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyProcessStatus.
func (in *EnvoyProcessStatus) DeepCopy() *EnvoyProcessStatus {
	if in == nil {
		return nil
	}
	out := new(EnvoyProcessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverStatus) DeepCopyInto(out *FailoverStatus) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	out.Source = in.Source
	if in.Candidate != nil {
		in, out := &in.Candidate, &out.Candidate
		*out = new(ProcessIdentity)
		**out = **in
	}
	if in.OffsetDeadline != nil {
		in, out := &in.OffsetDeadline, &out.OffsetDeadline
		*out = (*in).DeepCopy()
	}
	if in.EmptySince != nil {
		in, out := &in.EmptySince, &out.EmptySince
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverStatus.
func (in *FailoverStatus) DeepCopy() *FailoverStatus {
	if in == nil {
		return nil
	}
	out := new(FailoverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkStatus) DeepCopyInto(out *NetworkStatus) {
	*out = *in
	if in.VerifiedAt != nil {
		in, out := &in.VerifiedAt, &out.VerifiedAt
		*out = (*in).DeepCopy()
	}
	if in.EnvoyProcesses != nil {
		in, out := &in.EnvoyProcesses, &out.EnvoyProcesses
		*out = make([]EnvoyProcessStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkStatus.
func (in *NetworkStatus) DeepCopy() *NetworkStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeMetricStatus) DeepCopyInto(out *NodeMetricStatus) {
	*out = *in
	in.CollectedAt.DeepCopyInto(&out.CollectedAt)
	if in.CPUMillicores != nil {
		in, out := &in.CPUMillicores, &out.CPUMillicores
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeMetricStatus.
func (in *NodeMetricStatus) DeepCopy() *NodeMetricStatus {
	if in == nil {
		return nil
	}
	out := new(NodeMetricStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStatus) DeepCopyInto(out *NodeStatus) {
	*out = *in
	if in.Replication != nil {
		in, out := &in.Replication, &out.Replication
		*out = new(ReplicationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Observation != nil {
		in, out := &in.Observation, &out.Observation
		*out = new(ProcessObservationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Recovery != nil {
		in, out := &in.Recovery, &out.Recovery
		*out = new(ProcessRecoveryStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Termination != nil {
		in, out := &in.Termination, &out.Termination
		*out = new(ProcessTermination)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStatus.
func (in *NodeStatus) DeepCopy() *NodeStatus {
	if in == nil {
		return nil
	}
	out := new(NodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessIdentity) DeepCopyInto(out *ProcessIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessIdentity.
func (in *ProcessIdentity) DeepCopy() *ProcessIdentity {
	if in == nil {
		return nil
	}
	out := new(ProcessIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessObservationStatus) DeepCopyInto(out *ProcessObservationStatus) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	if in.TransportErrorSince != nil {
		in, out := &in.TransportErrorSince, &out.TransportErrorSince
		*out = (*in).DeepCopy()
	}
	if in.BusySince != nil {
		in, out := &in.BusySince, &out.BusySince
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessObservationStatus.
func (in *ProcessObservationStatus) DeepCopy() *ProcessObservationStatus {
	if in == nil {
		return nil
	}
	out := new(ProcessObservationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessRecoveryStatus) DeepCopyInto(out *ProcessRecoveryStatus) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	if in.DeleteRequestedAt != nil {
		in, out := &in.DeleteRequestedAt, &out.DeleteRequestedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessRecoveryStatus.
func (in *ProcessRecoveryStatus) DeepCopy() *ProcessRecoveryStatus {
	if in == nil {
		return nil
	}
	out := new(ProcessRecoveryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessTermination) DeepCopyInto(out *ProcessTermination) {
	*out = *in
	in.FinishedAt.DeepCopyInto(&out.FinishedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessTermination.
func (in *ProcessTermination) DeepCopy() *ProcessTermination {
	if in == nil {
		return nil
	}
	out := new(ProcessTermination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationStatus) DeepCopyInto(out *ReplicationStatus) {
	*out = *in
	if in.SyncedAt != nil {
		in, out := &in.SyncedAt, &out.SyncedAt
		*out = (*in).DeepCopy()
	}
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationStatus.
func (in *ReplicationStatus) DeepCopy() *ReplicationStatus {
	if in == nil {
		return nil
	}
	out := new(ReplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutStatus) DeepCopyInto(out *RolloutStatus) {
	*out = *in
	if in.Process != nil {
		in, out := &in.Process, &out.Process
		*out = new(ProcessIdentity)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutStatus.
func (in *RolloutStatus) DeepCopy() *RolloutStatus {
	if in == nil {
		return nil
	}
	out := new(RolloutStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceCredentials) DeepCopyInto(out *ServiceCredentials) {
	*out = *in
	if in.OperatorPassword != nil {
		in, out := &in.OperatorPassword, &out.OperatorPassword
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.ReplicaPassword != nil {
		in, out := &in.ReplicaPassword, &out.ReplicaPassword
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.HealthPassword != nil {
		in, out := &in.HealthPassword, &out.HealthPassword
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.UsersACL != nil {
		in, out := &in.UsersACL, &out.UsersACL
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceCredentials.
func (in *ServiceCredentials) DeepCopy() *ServiceCredentials {
	if in == nil {
		return nil
	}
	out := new(ServiceCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeyInstance) DeepCopyInto(out *ValkeyInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeyInstance.
func (in *ValkeyInstance) DeepCopy() *ValkeyInstance {
	if in == nil {
		return nil
	}
	out := new(ValkeyInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ValkeyInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeyInstanceList) DeepCopyInto(out *ValkeyInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ValkeyInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeyInstanceList.
func (in *ValkeyInstanceList) DeepCopy() *ValkeyInstanceList {
	if in == nil {
		return nil
	}
	out := new(ValkeyInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ValkeyInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeyInstanceSpec) DeepCopyInto(out *ValkeyInstanceSpec) {
	*out = *in
	if in.Whitelist != nil {
		in, out := &in.Whitelist, &out.Whitelist
		*out = new(WhitelistSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeyInstanceSpec.
func (in *ValkeyInstanceSpec) DeepCopy() *ValkeyInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(ValkeyInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValkeyInstanceStatus) DeepCopyInto(out *ValkeyInstanceStatus) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.PrimaryOrdinal != nil {
		in, out := &in.PrimaryOrdinal, &out.PrimaryOrdinal
		*out = new(int32)
		**out = **in
	}
	if in.AcceptedConfiguration != nil {
		in, out := &in.AcceptedConfiguration, &out.AcceptedConfiguration
		*out = new(AcceptedConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Applied != nil {
		in, out := &in.Applied, &out.Applied
		*out = new(AppliedConfiguration)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Failover != nil {
		in, out := &in.Failover, &out.Failover
		*out = new(FailoverStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Rollout != nil {
		in, out := &in.Rollout, &out.Rollout
		*out = new(RolloutStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CredentialRotation != nil {
		in, out := &in.CredentialRotation, &out.CredentialRotation
		*out = new(CredentialRotationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Deletion != nil {
		in, out := &in.Deletion, &out.Deletion
		*out = new(DeletionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]NodeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreviousProcesses != nil {
		in, out := &in.PreviousProcesses, &out.PreviousProcesses
		*out = make([]NodeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]NodeMetricStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValkeyInstanceStatus.
func (in *ValkeyInstanceStatus) DeepCopy() *ValkeyInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(ValkeyInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WhitelistSpec) DeepCopyInto(out *WhitelistSpec) {
	*out = *in
	if in.CIDRs != nil {
		in, out := &in.CIDRs, &out.CIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WhitelistSpec.
func (in *WhitelistSpec) DeepCopy() *WhitelistSpec {
	if in == nil {
		return nil
	}
	out := new(WhitelistSpec)
	in.DeepCopyInto(out)
	return out
}
