apiVersion: v1
kind: Namespace
metadata:
  name: mv-verify-restart-policy
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: mv-verify-restart-policy
spec:
  clusterIP: None
  selector:
    app: valkey-restart-verification
  ports:
    - name: valkey
      port: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
  namespace: mv-verify-restart-policy
spec:
  serviceName: valkey
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: valkey-restart-verification
  template:
    metadata:
      labels:
        app: valkey-restart-verification
      finalizers:
        - valkey.h3llo-demo.com/process-stopped
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: valkey
          image: valkey/valkey:8.1.9
          imagePullPolicy: IfNotPresent
          restartPolicy: Never
          ports:
            - name: valkey
              containerPort: 6379
