defaultArgs:
  - --cert-dir=/tmp
  - --kubelet-preferred-address-types=Hostname,InternalDNS,InternalIP,ExternalDNS,ExternalIP
  - --kubelet-use-node-status-port
  - --metric-resolution=15s

args:
  - --kubelet-certificate-authority=/etc/kubelet-ca/ca.crt

extraVolumeMounts:
  - name: kubelet-ca
    mountPath: /etc/kubelet-ca
    readOnly: true

extraVolumes:
  - name: kubelet-ca
    configMap:
      name: metrics-server-kubelet-ca
